export default function FairnessPage() {
  return (
    <div className="max-w-4xl mx-auto space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="bg-[#15181f] border border-[#2a2d3a] rounded-2xl p-8 relative overflow-hidden shadow-[0_8px_30px_rgba(0,0,0,0.5)]">
        {/* Background Accent */}
        <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-accent-blue/5 rounded-full blur-[100px] pointer-events-none translate-x-1/2 -translate-y-1/2" />
        
        <div className="relative z-10">
          <div className="flex items-center gap-3 mb-6">
            <div className="p-3 bg-accent-blue/10 rounded-xl border border-accent-blue/20">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-accent-blue"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/><path d="m9 12 2 2 4-4"/></svg>
            </div>
            <h1 className="text-3xl font-black text-white uppercase tracking-wider">Provably Fair</h1>
          </div>
          
          <p className="text-[#8e95ad] leading-relaxed text-lg max-w-3xl">
            Our platform uses a cryptographic provably fair system to ensure that all game results are truly random and completely unalterable by the house. Every roll can be mathematically verified.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="bg-[#15181f] border border-[#2a2d3a] rounded-xl p-6 shadow-lg">
          <h3 className="text-white font-bold text-lg mb-2 flex items-center gap-2">
            <div className="w-6 h-6 rounded bg-purple-500/20 text-purple-400 flex items-center justify-center text-xs">1</div>
            Server Seed
          </h3>
          <p className="text-[#7a819c] text-sm leading-relaxed">
            A secret random string generated by our server before the game starts. We provide you with its hashed version (SHA-256) so you know it wasn't changed after you place your bet.
          </p>
        </div>
        
        <div className="bg-[#15181f] border border-[#2a2d3a] rounded-xl p-6 shadow-lg">
          <h3 className="text-white font-bold text-lg mb-2 flex items-center gap-2">
            <div className="w-6 h-6 rounded bg-blue-500/20 text-blue-400 flex items-center justify-center text-xs">2</div>
            Client Seed
          </h3>
          <p className="text-[#7a819c] text-sm leading-relaxed">
            A string that you can choose or let your browser generate. This ensures that you have direct influence over the final outcome, making it impossible for the server to rig the result.
          </p>
        </div>

        <div className="bg-[#15181f] border border-[#2a2d3a] rounded-xl p-6 shadow-lg">
          <h3 className="text-white font-bold text-lg mb-2 flex items-center gap-2">
            <div className="w-6 h-6 rounded bg-green-500/20 text-green-400 flex items-center justify-center text-xs">3</div>
            Nonce
          </h3>
          <p className="text-[#7a819c] text-sm leading-relaxed">
            A number that increments with every bet you place. This ensures that even if the Server Seed and Client Seed remain the same, every single roll generates a completely unique result.
          </p>
        </div>
      </div>

      <div className="bg-[#15181f] border border-[#2a2d3a] rounded-xl p-8 shadow-[0_8px_30px_rgba(0,0,0,0.5)]">
        <h2 className="text-2xl font-black text-white mb-6">How The Math Works</h2>
        
        <p className="text-[#8e95ad] mb-6">
          To generate the outcome, we combine the three variables using an HMAC-SHA256 signature. The resulting hex string is converted into a decimal number, which determines the roll result.
        </p>

        <div className="bg-[#0f1115] border border-[#2a2d3a] rounded-lg p-6 font-mono text-sm overflow-x-auto">
          <div className="text-blue-400 mb-2">{'// Example Roll Generation (Node.js)'}</div>
          <div className="text-[#8e95ad]">
            <span className="text-purple-400">const</span> crypto = require(<span className="text-green-400">'crypto'</span>);<br/><br/>
            <span className="text-purple-400">const</span> serverSeed = <span className="text-green-400">'server_secret_seed'</span>;<br/>
            <span className="text-purple-400">const</span> clientSeed = <span className="text-green-400">'your_client_seed'</span>;<br/>
            <span className="text-purple-400">const</span> nonce = <span className="text-yellow-400">1</span>;<br/><br/>
            
            <span className="text-blue-400">{'// Combine Client Seed and Nonce'}</span><br/>
            <span className="text-purple-400">const</span> payload = <span className="text-green-400">`</span><span className="text-blue-300">${'{clientSeed}'}</span><span className="text-green-400">:</span><span className="text-blue-300">${'{nonce}'}</span><span className="text-green-400">`</span>;<br/><br/>
            
            <span className="text-blue-400">{'// Create HMAC-SHA256 hash'}</span><br/>
            <span className="text-purple-400">const</span> hash = crypto.createHmac(<span className="text-green-400">'sha256'</span>, serverSeed).update(payload).digest(<span className="text-green-400">'hex'</span>);<br/><br/>
            
            <span className="text-blue-400">{'// Take first 8 characters and convert to integer'}</span><br/>
            <span className="text-purple-400">const</span> subHash = hash.substring(<span className="text-yellow-400">0</span>, <span className="text-yellow-400">8</span>);<br/>
            <span className="text-purple-400">const</span> rollNumber = parseInt(subHash, <span className="text-yellow-400">16</span>);<br/><br/>
            
            <span className="text-blue-400">{'// Calculate modulo depending on game type (e.g. 0-99 for dice)'}</span><br/>
            <span className="text-purple-400">const</span> finalResult = rollNumber % <span className="text-yellow-400">100</span>;<br/>
          </div>
        </div>
      </div>
    </div>
  );
}
