import { Client } from 'growtopia.js';
import axios from 'axios';

// ==========================================
// CONFIGURATION
// ==========================================
const BOT_USERNAME = process.env.GROWTOPIA_BOT_USERNAME || 'GrowSpinDeposit';
const BOT_PASSWORD = process.env.GROWTOPIA_BOT_PASSWORD || 'password123';
const BACKEND_URL = process.env.BACKEND_URL || 'http://localhost:3001';
const BOT_SECRET = process.env.GROWTOPIA_BOT_SECRET || 'GROWTOPIA_BOT_SECRET_2026'; // Must match backend/index.ts

// The bot connects to Growtopia
const bot = new Client();

bot.on('ready', () => {
  console.log(`✅ [BOT] Connected as ${bot.name}`);
  // In a real scenario, the bot would likely loop through worlds generated by /api/deposit/request
  // Or it would stay in a master world and users would drop there. 
  // Our backend creates a unique world per deposit intent.
});

// Listen for items dropped (Diamond Locks = item ID 1796)
bot.on('onDrop', async (data) => {
  console.log(`[BOT] Item Dropped: ID ${data.itemID}, Count ${data.count}`);
  
  if (data.itemID === 1796) { // Diamond Lock
    const dlCount = data.count;
    // 1 DL = 100 subunits in the casino balance system
    const amountToCredit = dlCount * 100;
    
    // Who dropped it? The bot receives player info in the packet.
    // For this example, we assume we extract the growId from the world or player nearby.
    const growId = "PLAYER_WHO_DROPPED_IT"; 

    console.log(`[BOT] Detected ${dlCount} DL drop from ${growId}. Sending credit to backend...`);
    
    try {
      const res = await axios.post(`${BACKEND_URL}/api/internal/bot/credit`, {
        secret: BOT_SECRET,
        growId: growId, 
        amount: amountToCredit
      });
      
      console.log(`✅ [BOT] Successfully credited ${growId}. New balance: ${res.data.newBalance}`);
      
      // Optionally collect the DL
      // bot.collect(data.netID);
    } catch (err) {
      console.error(`❌ [BOT] Failed to credit user:`, err?.response?.data || err.message);
    }
  }
});

bot.login({
  mac: '00:00:00:00:00:00', // Spoofed mac
  tankIDName: BOT_USERNAME,
  tankIDPass: BOT_PASSWORD
});
